name: Dan.Common CI Nuget

on:
  push:
    branches:
    - master
    paths:
      - 'Dan.Common/**'
      - '!**/*.md'
      - '!**/*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup build environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Set VERSION variable from latest tag (if existing) plus date and commit
      run: |
        LATEST_TAG=$(git ls-remote --tags origin | tail -n 1 | awk '{ print $2; }' | sed 's/.*tags\/v//')
        echo "LATEST_TAG: ${LATEST_TAG}"
        LATEST_TAG=${LATEST_TAG:=0.0.1}
        VERSION=${LATEST_TAG}-next.$(date +%Y%m%d).${GITHUB_RUN_NUMBER}
        echo "VERSION: ${VERSION}"
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Set PROJECT variable to point to solution file
      run: |
        PROJECT=$(find . -name 'Dan.Common.csproj' -printf "%p" -quit)
        echo "PROJECT: ${PROJECT}"
        echo "PROJECT=${PROJECT}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} ${PROJECT}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build ${PROJECT}
    - name: Pack with debug symbols
      run: dotnet pack --configuration Release /p:Version=${VERSION} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output . ${PROJECT}
    - name: Push to GitHub Packages
      run: dotnet nuget push *.${VERSION}.nupkg --source https://nuget.pkg.github.com/${GITHUB_REPOSITORY%/*}/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
