name: Post deploy test
on:
 workflow_dispatch:
jobs:
 run:
   uses: data-altinn-no/deploy-actions/.github/workflows/post-deploy-test.yml@main
   with:
     environment: 'dev'
   secrets:
     azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
     kvname: ${{ secrets.KVNAME }}
